api_v1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home_page,name="main_home" ),
    path('login/', views.loginpage, name="login"),
    path('resume/', views.resume, name="resume"),
    path('download/', views.download_pdf, name="download")

]

csengineerbro/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('api_v1.urls', 'api_v1'), namespace = 'api_v1')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api_v1/models.py
from django.db import models

# Create your models here.
class PersonalInformation(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    avatar = models.URLField(blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)
    cv = models.FileField(upload_to='cv', blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    hackerrank = models.URLField(blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    twitter = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    mycv = models.URLField(blank=True, null=True)



class About(models.Model):
    title = models.CharField(max_length=20, blank=True, null=True)
    description1 = models.TextField(blank=False, null=True)
    description2 = models.TextField(blank=False, null=True)
    about_avatar = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title


class Projects(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    skill = models.TextField(max_length=230, blank=True, null=True)
    link = models.URLField(blank=True, null=True)
    image = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title


class Contact(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)

    email = models.EmailField(max_length=255, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    msg = models.TextField(max_length=100, blank=True, null=True)
    link = models.URLField(blank=True, null=True)
    image = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    twitter = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title


class Skills(models.Model):
    skill = models.CharField(max_length=50, blank=True, null=True)
    num = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.skill

api_v1/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponse
from wsgiref.util import FileWrapper
import os


# Create your views here.


def home_page(request):
    myinfo = PersonalInformation.objects.all()
    myabout = About.objects.all()
    myskills = Projects.objects.all()
    skills = Skills.objects.all()
    context = {
        "info": myinfo,
        "about": myabout,
        "skills": myskills,
        "know": skills
    }

    return render(request, 'home.html', context)

def loginpage(request):
    return render(request, 'login.html')

def resume(request):
    myinfo = PersonalInformation.objects.all()
    myabout = About.objects.all()
    myskills = Projects.objects.all()
    skills = Skills.objects.all()
    context = {
        "info": myinfo,
        "about": myabout,
        "skills": myskills,
        "know": skills
    }
    return render(request, 'resume.html', context)


import mimetypes
# import os module
import os
# Import HttpResponse module
from django.http.response import HttpResponse


def download_pdf(request):
    filename = "AZAD_KHAN.pdf"
    filepath = os.getcwd() +'/media/cv/'+ filename
    path = open(filepath, 'rb')
    response = HttpResponse(path, content_type='application/pdf')
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Azad{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body style="background-color: rgb(146, 221, 221);">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Azad Khan</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'api_v1:main_home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'api_v1:resume' %}">Resume</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success me-2" type="submit">Search</button>
                </form>
                <a href="{% url 'api_v1:login' %}" class="btn btn-outline-success my-2">Make an account</a>
              </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>

        
    <footer class="text-center text-lg-start text-white bg-dark" style="background-color: #067a30e9">
        <div class="container p-4 pb-0">
            <section>
                <div class="text-center p-3" style="background-color: rgba(3, 3, 3, 0.2);">
                © All right Reversed
                </div>
            </section>
        </div>
    </footer>
</body>
</html>

templates/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Azad Portfolio{% endblock %}
{% block content %}


<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5" style="padding: 50px;">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Azad Khan</h1>
        <hr class="featurette-divider">
        <h6 class="header-mono">Backend Developer | Python</h6>
      </div>
    </div>
  </section>


   <!--<section class="py-5 container">
      <h1 class="h1 fw-bold">Summary</h1>
      <p class="mb-0">Specializes in contributing to a highly collaborative work environment, finding solutions, and determining
        customersatisfaction. Web applications are designed and developed across multiple APIs,third-party 
        integrations, and databases. Passionate and hardworking with a passion for efficiently performing tasks.</p>
    <hr class="featurette-divider">
  </section>


  <section class="py-5 container">
    <div>
      <h1 class="h1 fw-bold">Experience</h1>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Software Developer Intern, <span class="text-muted">May 2022 to Sep 2022</span></h2>
        <p class="lead text-muted" >Mcsam, Gurgoan</p>
        <ul>
          <li>Partnered with companymentorto learn best practicesin software design.</li>
          <li>Fix bugs and errorsin application software both frontend and backend</li>
          <li>Used development toolssuch as Django rest framework and Postman regularly.
          </li>
          <li>Analyzed source code to identify and rectify potential functionality issues.
          </li>
          <li>Utilize such technologies as Python, Django restframework, Angular, Html&CSS, and</li>
          <li>MySQL to develop new functionality in the application.</li>
        </ul>  
      </div>
      <div class="col-md-5">
        <img src = "/static/images/mcsam.png" alt="Mcsam India"/ width="500", height="200">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">DevOps Engineer Intern, <span class="text-muted">Feb 2022 to Apr 2022</span></h2>
        <p class="lead text-muted" >Bolingbrook Illinois, United States</p>
        <ul>
          <li>Quickly learned new skills and applied themto daily tasks.</li>
          <li>Carried out day-to-day duties accurately and efficiently.</li>
          <li>Hands-on experience in Terraform.</li>
          <li>Learn AZ-900: Microsoft Azure Fundamentals.</li>
          <li>Translating requirements and functionalspecificationsinto Data.</li>
          <li>Infrastructure as Code(Iac).</li>
        </ul>
      </div>
      <div class="col-md-5 order-md-1">
        <img src="/static/images/ismile_main.png" alt="Ismile Technologies", width="500", height="200" style="padding-top: 20px;">
      </div>
    </div>
  
    <hr class="featurette-divider">
  </section>


  <section class="py-5 container">
    <div>
      <h1 class="h1 fw-bold">Skills</h1>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7">
        <ul>
          <li>Python</li>
          <li>Html CSS</li>
          <li>Java</li>
          <li>Angular</li>
          <li>Django Rest Framework</li>
        </ul>  
      </div>

      <div class="col-md-5">
        <ul>
          <li>Azure</li>
          <li>Postman API</li>
          <li>Terraform</li>
          <li>Mysql</li>
          <li>Github</li>
        </ul>  
      </div>
    </div>

    <hr class="featurette-divider">
  </section>

  <section class="py-5 container">
    <div>
      <h1 class="h1 fw-bold">Projects</h1>
    </div>
    <hr class="featurette-divider">
      <div class="row py-lg-5">
        <ol>
          <li style="font-size: 1.5em">
            <h4 class="featurette-heading fw-normal lh-1">Image Blurring and Deblurring, <span class="text-muted">Aug 2021 to Apr 2022</span></h4>
          </li>
          <ul>
            <li>I have taken Kaggle dataset high-resolution Images and usedGaussian blur for adding
            noise and reduce the resolution</li>
            <li>Use such technologies as Python, Matplotlib, Pandas, and OpenCV.</li>
            <li>Used development toolssuch as Django rest framework and Postman regularly.</li>
            <li>Apply SRCNNarchitecture for deblurring the blurred Images</li>
          </ul>
          <br> 
          <li style="font-size: 1.5em">
            <h4 class="featurette-heading fw-normal lh-1">Rental Website, <span class="text-muted">Feb 2021 to May 2022</span></h4>
          </li>
            <ul>
              <li>Website in which Users can register and search perfect place to live,rent a house and buy a plot.</li>
              <li>
                Build this webpage using Html, CSS, and JavaScript.
            </ul> 
        </ol> 
    </div>
    <hr class="featurette-divider">
  </section> -->
</main>

{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>SignUp and Login-weildly</title>
	 <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" href="https://fonts.googleapis.com/css?family=Sofia">
 
    <link rel="shortcut icon" href= "/static/images/on_my_way_by.jpg">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href= "/static/images/on_my_way_by.jpg">
    <link rel=stylesheet href="/static/css/loginpage.css">
	<style>
		body {
		  background-image: url('/static/images/on_my_way_by.jpg');
		}
		</style>
</head>
<body>

<div class="container" id="container">
<div class="form-container sign-up-container">

<form action="">
	<h1>Create Account</h1>
	<div class="social-container">
		<a href="#" class="social"><i class="fa fa-facebook"></i></a>
		<a href="#" class="social"><i class="fa fa-google"></i></a>
		<a href="#" class="social"><i class="fa fa-linkedin"></i></a>
	</div>
	<span>or use your email for registration</span>
	<input type="text" name="name" placeholder="Name">
	<input type="email" name="email" placeholder="Email">
	<input type="password" name="password" placeholder="Password">
	<button>SignUp</button>
</form>
</div>
<div class="form-container sign-in-container">
	<form action="#">
		<h1>Sign In</h1>
		<div class="social-container">
		<a href="#" class="social"><i class="fa fa-facebook"></i></a>
		<a href="#" class="social"><i class="fa fa-google"></i></a>
		<a href="#" class="social"><i class="fa fa-linkedin"></i></a>
	</div>
	<span>or use your account</span>
	<input type="email" name="email" placeholder="Email">
	<input type="password" name="password" placeholder="Password">
	<a href="#">Forgot Your Password</a>

	<button>Sign In</button>
	</form>
</div>
<div class="overlay-container">
	<div class="overlay">
		<div class="overlay-panel overlay-left">
			<h1>Welcome Back!</h1>
			<p>To keep connected with us please login with your personal info</p>
			<button class="ghost" id="signIn">Sign In</button>
		</div>
		<div class="overlay-panel overlay-right">
			<h1>Hello, Friend!</h1>
			<p>Enter your details and start journey with us</p>
			<button class="ghost" id="signUp">Sign Up</button>
		</div>
	</div>
</div>
</div>

<script type="text/javascript">
	const signUpButton = document.getElementById('signUp');
	const signInButton = document.getElementById('signIn');
	const container = document.getElementById('container');

	signUpButton.addEventListener('click', () => {
		container.classList.add("right-panel-active");
	});
	signInButton.addEventListener('click', () => {
		container.classList.remove("right-panel-active");
	});
</script>


</body>
</html>

templates/resume.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Azad Resume{% endblock %}
{% block content %}


<main>
  <section class="py-5 text-center container" style="background-color: black;">
    <div class="row py-lg-5" style="padding: 50px;">
      <div class="col-lg-6 col-md-8 mx-auto">
        <p id="hey" style="color:aqua;">HEY THERE !</p>
        {% for infor in info %}
        <h1 id="name" class="h1 fw-bold text-white my-2 me-2">I'm <span>{{infor.name}}</span> </h1>
        <h3 class="h3 fw-bold text-muted my-5"> A Backend Developer | Python</h3>
        <p> <span id="big"></span>{{infor.mini_about}}</p>

        <div class="social">
            <a href="{{infor.instagram}}"> <i class="fa fa-instagram me-4" style="font-size:24px; color: aqua;"></i></a>
            <a href="{{infor.linkedin}}"><i class="fa fa-linkedin me-4"style="font-size:24px; color: aqua;"></i></a>
            <a href="{{infor.twitter}}"> <i class="fa fa-twitter me-4" style="font-size:24px; color: aqua;"></i></a>
            <a href="{{infor.github}}"><i class="fa fa-github me-4" style="font-size:24px; color: aqua;"></i></a>
        </div>
        <div class="button">
            <a href="mailto:{{infor.email}}"> <button class="btn btn-success my-4 me-4">Contact me</button></a>
            <a href="{% url 'api_v1:download' %}" class="btn btn-success my-5">Download Resume</a>
            <!-- <a class="main-button ml-2" href="{{infor.mycv}}" target="_blank" rel="noopener noreferrer"> <button id="btn2" class="btn btn-success me-4">My Resume <i class="uil uil-import"></i></i> -->
            </button></a>

        </div>
        <div class="col-md-6 initial-1 aos-init" data-aos="zoom-in" data-aos-delay="300">
            <img src="{{infor.avatar}}" alt="">
        </div>
        {% endfor %}
      </div>
    </div>
  </section>


  <section class="py-5 container">
      <h1 class="h1 fw-bold">Summary</h1>
      {% for infor in info %}
      <p class="mb-0">{{infor.summary}}</p>
      {% endfor %}
    <hr class="featurette-divider">
  </section>


  <section class="py-5 container">
    <div>
      <h1 class="h1 fw-bold">Experience</h1>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Software Developer Intern, <span class="text-muted">May 2022 to Sep 2022</span></h2>
        <p class="lead text-muted" >Mcsam, Gurgoan</p>
        <ul>
          <li>Partnered with companymentorto learn best practicesin software design.</li>
          <li>Fix bugs and errorsin application software both frontend and backend</li>
          <li>Used development toolssuch as Django rest framework and Postman regularly.
          </li>
          <li>Analyzed source code to identify and rectify potential functionality issues.
          </li>
          <li>Utilize such technologies as Python, Django restframework, Angular, Html&CSS, and</li>
          <li>MySQL to develop new functionality in the application.</li>
        </ul>  
      </div>
      <div class="col-md-5">
        <img src = "/static/images/mcsam.png" alt="Mcsam India"/ width="500", height="200">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">DevOps Engineer Intern, <span class="text-muted">Feb 2022 to Apr 2022</span></h2>
        <p class="lead text-muted" >Bolingbrook Illinois, United States</p>
        <ul>
          <li>Quickly learned new skills and applied themto daily tasks.</li>
          <li>Carried out day-to-day duties accurately and efficiently.</li>
          <li>Hands-on experience in Terraform.</li>
          <li>Learn AZ-900: Microsoft Azure Fundamentals.</li>
          <li>Translating requirements and functionalspecificationsinto Data.</li>
          <li>Infrastructure as Code(Iac).</li>
        </ul>
      </div>
      <div class="col-md-5 order-md-1">
        <img src="/static/images/ismile_main.png" alt="Ismile Technologies", width="500", height="200" style="padding-top: 20px;">
      </div>
    </div>
  
    <hr class="featurette-divider">
  </section>


  <section class="py-5 container">
    <div>
      <h1 class="h1 fw-bold">Skills</h1>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7">
        <ul>
          <li>Python</li>
          <li>Html CSS</li>
          <li>Java</li>
          <li>Angular</li>
          <li>Django Rest Framework</li>
        </ul>  
      </div>

      <div class="col-md-5">
        <ul>
          <li>Azure</li>
          <li>Postman API</li>
          <li>Terraform</li>
          <li>Mysql</li>
          <li>Github</li>
        </ul>  
      </div>
    </div>

    <hr class="featurette-divider">
  </section>

  <section class="py-5 container">
    <div>
      <h1 class="h1 fw-bold">Projects</h1>
    </div>
    <hr class="featurette-divider">
      <div class="row py-lg-5">
        <ol>
          <li style="font-size: 1.5em">
            <h3 class="featurette-heading fw-normal lh-1">Image Blurring and Deblurring, <span class="text-muted">Aug 2021 to Apr 2022</span></h3>
          </li>
          <ul>
            <li>I have taken Kaggle dataset high-resolution Images and usedGaussian blur for adding
            noise and reduce the resolution</li>
            <li>Use such technologies as Python, Matplotlib, Pandas, and OpenCV.</li>
            <li>Used development toolssuch as Django rest framework and Postman regularly.</li>
            <li>Apply SRCNNarchitecture for deblurring the blurred Images</li>
          </ul>
          <br> 
          <li style="font-size: 1.5em">
            <h3 class="featurette-heading fw-normal lh-1">Rental Website, <span class="text-muted">Feb 2021 to May 2022</span></h3>
          </li>
            <ul>
              <li>Website in which Users can register and search perfect place to live,rent a house and buy a plot.</li>
              <li>
                Build this webpage using Html, CSS, and JavaScript.
            </ul> 
        </ol> 
    </div>
    <hr class="featurette-divider">
  </section>

  <section class="py-5 container">
    <div>
      <h1 class="h1 fw-bold">Education</h1>
    </div>
    <hr class="featurette-divider">
    <div class="row py-lg-5">
        <h2 class="featurette-heading fw-normal lh-1">B.Tech: <span class="text-muted">Computer Science Engineering, 07/2022</span></h2>
        <h2 class="featurette-heading fw-normal lh-1">Galgotia College of Engineering & technology - <span class="text-muted">Greater Noida, Uttar Pradesh</span></h2>
    </div>
    <br>
    <div class="row py-lg-5">
        <h3 class="featurette-heading fw-normal lh-1">INTERMEDIATE: <span class="text-muted">PCM, 06/2017</span></h3>
        <h3 class="featurette-heading fw-normal lh-1">J. SHIKSHAN S. I. C. JAMON - <span class="text-muted">Amethi, Uttar Pradesh</span></h4>
    </div>
  
    <hr class="featurette-divider">
    <div>
        <p class="mb-0 text-center">This is to declare that all the above entries are true to the best of my knowledge.</p>
    </div>
  </section>

</main>

{% endblock %}